[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "sh /railway-entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
APP_ENV = "production"
APP_TITLE = "Flowndly"
TELEMETRY_ENABLED = "false"
PROTOCOL = "https"
PORT = "3000"
WORKER = "false"
